SELECT TOP (10) [Transaction_ID]
      ,[Customer_ID]
      ,[Account_ID]
      ,[Transaction_Type]
      ,[Channel]
      ,[Currency]
      ,[Amount]
      ,[Transaction_Date]
      ,[Balance_Before]
      ,[Balance_After]
      ,[Fraud_Flag]
      ,[Risk_Score]
      ,[Region]
      ,[Load_Date]
  FROM [FinancialAnalyticsDB].[staging].[stg_transactions]
